Repository monsij/StudentPortal, pull requests merged in 2018-12, with the labels that each got.

#10 Added favicon and some additional files
  pro1/blog/static/blog/css/main.css
  pro1/blog/static/blog/css/style.css
  pro1/blog/static/blog/images/dgpicon.png
  pro1/blog/static/blog/js/bootstrap.min.js
  pro1/blog/static/blog/js/jquery.min.js
  pro1/blog/static/blog/js/script.js
  pro1/blog/templates/blog/base.html
  pro1/pro1/settings.py
Labels: process/pending_review, size/S

#18 contributor.html: Fix typo
  pro1/blog/templates/blog/contributor.html
Labels: size/XS, status/approved

#17 Updates
  pro1/blog/templates/blog/base.html
  pro1/pro1/settings.py
Labels: size/XS, status/approved

#16 Introduced new navbar
  pro1/blog/static/blog/css/style.css
  pro1/blog/templates/blog/base.html
  pro1/db.sqlite3
Labels: process/pending_review, size/XS

#24 Removed Unwanted Comments
  pro1/blog/urls.py
  pro1/interviews/views.py
  pro1/noticeboard/views.py
  pro1/pro1/settings.py
  pro1/study/views.py
  pro1/users/views.py
Labels: size/XS, status/approved

#34 Issue: #29
  pro1/blog/templates/blog/contributor.html
Labels: size/XS, status/approved

#36 Update README.md
  README.md
Labels: size/XS, status/approved

#37 Updated CONTRIBUTING.rst
  CONTRIBUTING.rst
Labels: size/XS, status/approved

#33 Dynamic sync for contributors page
  pro1/blog/static/blog/images/codingBG.jpg
  pro1/blog/static/blog/images/gopavasanth.jpeg
  pro1/blog/static/blog/images/gutsytechster.jpeg
  pro1/blog/static/blog/images/harry-hov.jpeg
  pro1/blog/static/blog/images/monsij.jpeg
  pro1/blog/static/blog/images/r3trd.jpeg
  pro1/blog/static/blog/js/card.js
  pro1/blog/static/blog/jsGit/widget.js
  pro1/blog/templates/blog/contributor.html
  pro1/blog/templates/blog/gitCard/medium.html
  pro1/blog/urls.py
  pro1/blog/views.py
Labels: size/L, status/approved

#41 resolved uneven card size
  pro1/blog/templates/blog/gitCard/medium.html
Labels: size/XS, status/approved

#42 Fixed Time and IP not displayed bug
  pro1/blog/templates/blog/base.html
Labels: size/XS, status/approved

#44 Fixed current IP
  pro1/blog/templates/blog/base.html
Labels: size/XS, status/approved

#48 Added Travis CI configuration
  .travis.yml
  pro1/procfile
Labels: size/XS, status/approved

#55 Add contacts
  pro1/blog/templates/blog/contact.html
Labels: size/XS, status/approved

#60 Updated screenshot
  screenshots/P1.PNG
  screenshots/P2.PNG
  screenshots/P3.PNG
  screenshots/P4.PNG
  screenshots/P5.PNG
  screenshots/P6.PNG
  screenshots/P7.PNG
  screenshots/p8.png
  screenshots/p9.png
Labels: size/XS, status/approved

#62 README edited
  README.md
Labels: size/XS, status/approved

#64 Added codecov coverage configuration
  .travis.yml
  codecov.yml
Labels: size/XS

#58 sidebar is moved to bottom
  pro1/blog/static/blog/css/style.css
  pro1/blog/templates/blog/base.html
  pro1/blog/templates/blog/contributor.html
  pro1/blog/templates/blog/home.html
Labels: size/S

#71 #68 Link Hover
  pro1/blog/static/blog/css/style.css
Labels: process/pending_review, size/XS

#81 updated readme
  README.md
Labels: process/pending_review, size/XS

#82 updated chanakya portal link
  pro1/blog/templates/blog/base.html
Labels: process/pending_review, size/XS

#80 Page title format changed
  pro1/.gitignore
  pro1/blog/__pycache__/__init__.cpython-36.pyc
  pro1/blog/__pycache__/admin.cpython-36.pyc
  pro1/blog/__pycache__/apps.cpython-36.pyc
  pro1/blog/__pycache__/models.cpython-36.pyc
  pro1/blog/__pycache__/urls.cpython-36.pyc
  pro1/blog/__pycache__/views.cpython-36.pyc
  pro1/blog/migrations/__pycache__/__init__.cpython-36.pyc
  pro1/blog/templates/blog/about.html
  pro1/blog/templates/blog/contact.html
  pro1/blog/templates/blog/contributor.html
  pro1/blog/templates/blog/home.html
  pro1/catalog/__pycache__/__init__.cpython-36.pyc
  pro1/catalog/__pycache__/admin.cpython-36.pyc
  pro1/catalog/__pycache__/apps.cpython-36.pyc
  pro1/catalog/__pycache__/models.cpython-36.pyc
  pro1/catalog/migrations/__pycache__/__init__.cpython-36.pyc
  pro1/db.sqlite3
  pro1/interviews/__pycache__/__init__.cpython-36.pyc
  pro1/interviews/__pycache__/admin.cpython-36.pyc
  pro1/interviews/__pycache__/apps.cpython-36.pyc
  pro1/interviews/__pycache__/models.cpython-36.pyc
  pro1/interviews/__pycache__/urls.cpython-36.pyc
  pro1/interviews/__pycache__/views.cpython-36.pyc
  pro1/interviews/migrations/__pycache__/__init__.cpython-36.pyc
  pro1/interviews/templates/interviews/home.html
  pro1/noticeboard/__pycache__/__init__.cpython-36.pyc
  pro1/noticeboard/__pycache__/admin.cpython-36.pyc
  pro1/noticeboard/__pycache__/models.cpython-36.pyc
  pro1/noticeboard/__pycache__/urls.cpython-36.pyc
  pro1/noticeboard/__pycache__/views.cpython-36.pyc
  pro1/noticeboard/migrations/__pycache__/__init__.cpython-36.pyc
  pro1/noticeboard/templates/noticeboard/home.html
  pro1/pro1/__pycache__/__init__.cpython-36.pyc
  pro1/pro1/__pycache__/settings.cpython-36.pyc
  pro1/pro1/__pycache__/urls.cpython-36.pyc
  pro1/pro1/__pycache__/wsgi.cpython-36.pyc
  pro1/study/__pycache__/__init__.cpython-36.pyc
  pro1/study/__pycache__/admin.cpython-36.pyc
  pro1/study/__pycache__/apps.cpython-36.pyc
  pro1/study/__pycache__/models.cpython-36.pyc
  pro1/study/__pycache__/urls.cpython-36.pyc
  pro1/study/__pycache__/views.cpython-36.pyc
  pro1/study/migrations/__pycache__/__init__.cpython-36.pyc
  pro1/study/templates/study/home.html
  pro1/users/__pycache__/__init__.cpython-36.pyc
  pro1/users/__pycache__/admin.cpython-36.pyc
  pro1/users/__pycache__/apps.cpython-36.pyc
  pro1/users/__pycache__/forms.cpython-36.pyc
  pro1/users/__pycache__/models.cpython-36.pyc
  pro1/users/__pycache__/tokens.cpython-36.pyc
  pro1/users/__pycache__/views.cpython-36.pyc
  pro1/users/migrations/__pycache__/0001_initial.cpython-36.pyc
  pro1/users/migrations/__pycache__/0002_auto_20181103_0240.cpython-36.pyc
  pro1/users/migrations/__pycache__/0003_auto_20181103_0246.cpython-36.pyc
  pro1/users/migrations/__pycache__/0004_profile.cpython-36.pyc
  pro1/users/migrations/__pycache__/__init__.cpython-36.pyc
  pro1/users/templates/users/profile.html
Labels: process/pending_review, size/M

#70 about section fix in footer
  pro1/blog/templates/blog/base.html
Labels: size/S, status/approved

#93 Update README.md
  README.md
Labels: size/XS, status/approved

#84 Add Internship and Placement feature
  pro1/blog/static/blog/css/style.css
  pro1/blog/templates/blog/base.html
  pro1/interviews/admin.py
  pro1/interviews/migrations/0001_initial.py
  pro1/interviews/models.py
  pro1/interviews/templates/interviews/home.html
  pro1/interviews/templates/interviews/internship.html
  pro1/interviews/templates/interviews/placement.html
  pro1/interviews/urls.py
  pro1/interviews/views.py
Labels: assigned, enhancement, process/pending_review, size/M

#97 Add Label and Form link
  pro1/interviews/admin.py
  pro1/interviews/models.py
  pro1/interviews/templates/interviews/home.html
Labels: assigned, enhancement, help wanted, process/pending_review, size/XS

#91 Issue:#63 (First Year Study Zone Added)
  pro1/blog/templates/blog/base.html
  pro1/db.sqlite3
  pro1/pro1/settings.py
  pro1/pro1/urls.py
  pro1/study/templates/study/home.html
  pro1/study/templates/study/year_1/year_1.html
  pro1/year1/__init__.py
  pro1/year1/admin.py
  pro1/year1/apps.py
  pro1/year1/migrations/__init__.py
  pro1/year1/models.py
  pro1/year1/templates/year1/home.html
  pro1/year1/templates/year1/year_1_doc.html
  pro1/year1/tests.py
  pro1/year1/urls.py
  pro1/year1/views.py
Labels: process/pending_review, size/S
